# Generated by Django 2.1.12 on 2020-01-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPOrigen', models.IntegerField()),
                ('CiudadOrigen', models.CharField(max_length=254)),
                ('EstadoOrigen', models.CharField(max_length=254)),
                ('CPDestino', models.IntegerField(blank=True, null=True)),
                ('CiudadDestino', models.CharField(max_length=254)),
                ('EstadoDestino', models.CharField(max_length=254)),
                ('ViajeRedondo', models.BooleanField()),
                ('NombreRuta', models.CharField(max_length=254)),
                ('Kilometros', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Date_joined', models.DateTimeField(auto_now_add=True)),
                ('Date_Mod', models.DateTimeField(auto_now_add=True)),
                ('Casetas', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('Active', models.BooleanField(default=1)),
            ],
        ),
    ]
