# Generated by Django 2.1.12 on 2020-01-03 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rutas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rutas',
            name='IDUsuarioAlta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RutaAlta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rutas',
            name='IDUsuarioMod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RutaModi', to=settings.AUTH_USER_MODEL),
        ),
    ]
