# Generated by Django 2.1.12 on 2020-01-03 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kilometraje', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Tipo', models.CharField(max_length=254)),
                ('Producto', models.CharField(max_length=254)),
                ('TotalCostos', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Mop', models.DecimalField(decimal_places=2, max_digits=30)),
                ('MopPor', models.DecimalField(decimal_places=2, max_digits=30)),
                ('TotalTransportista', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Descripcion', models.TextField()),
                ('Active', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CostosOperativos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Combustible', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Casetas', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Operador', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Subtotal1', models.DecimalField(decimal_places=2, max_digits=30)),
                ('MttoUnidad', models.DecimalField(decimal_places=2, max_digits=30)),
                ('LlantasUnidad', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Gps', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Seguro', models.DecimalField(decimal_places=2, max_digits=30)),
                ('PlacasTenencia', models.DecimalField(decimal_places=2, max_digits=30)),
                ('SubTotal2', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Admvo', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Financieros', models.DecimalField(decimal_places=2, max_digits=30)),
                ('DeprUnidad', models.DecimalField(decimal_places=2, max_digits=30)),
                ('DeprRemolque', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Subtotal3', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutaid', models.IntegerField()),
                ('CpOrigen', models.IntegerField()),
                ('CpDestino', models.IntegerField()),
                ('Productos', models.CharField(max_length=254)),
                ('Peso', models.DecimalField(decimal_places=2, max_digits=30)),
                ('RangoPrecio', models.DecimalField(decimal_places=2, max_digits=30)),
                ('IDCosteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Costeo.Costeo')),
            ],
        ),
        migrations.CreateModel(
            name='Depreciacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meses', models.IntegerField()),
                ('CostosUnidad', models.DecimalField(decimal_places=2, max_digits=30)),
                ('CostosCaja', models.DecimalField(decimal_places=2, max_digits=30)),
                ('ViajesMes', models.IntegerField()),
                ('KmsMesXunidad', models.DecimalField(decimal_places=2, max_digits=30)),
                ('KmsMaximo', models.DecimalField(decimal_places=2, max_digits=30)),
                ('DepTracto', models.DecimalField(decimal_places=2, max_digits=30)),
                ('DepCaja', models.DecimalField(decimal_places=2, max_digits=30)),
                ('RentaGPS', models.DecimalField(decimal_places=2, max_digits=30)),
                ('PlacasTenencia', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Seguro', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Admvo', models.IntegerField()),
                ('Financieros', models.IntegerField()),
                ('MttoUnidadXkm', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Llantas', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Operador', models.DecimalField(decimal_places=2, max_digits=30)),
                ('DobleOp', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='FactoresPremisas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unidad', models.IntegerField()),
                ('Caja', models.IntegerField()),
                ('KmSencillo', models.DecimalField(decimal_places=2, max_digits=30)),
                ('KmRoundTrip', models.DecimalField(decimal_places=2, max_digits=30)),
                ('KmMensuales', models.DecimalField(decimal_places=2, max_digits=30)),
                ('CasetaSingle', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Rendimiento', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Diesel', models.DecimalField(decimal_places=2, max_digits=30)),
                ('DieselSinIva', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
        ),
    ]
