# Generated by Django 2.1.12 on 2020-01-03 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rutas', '0001_initial'),
        ('Costeo', '0001_initial'),
        ('Transportista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='IDTipoUnidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Transportista.UnidadType'),
        ),
        migrations.AddField(
            model_name='costeo',
            name='IDCostosOperativos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Costeo.CostosOperativos'),
        ),
        migrations.AddField(
            model_name='costeo',
            name='IDDepreciacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Costeo.Depreciacion'),
        ),
        migrations.AddField(
            model_name='costeo',
            name='IDFactoresPremisas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Costeo.FactoresPremisas'),
        ),
        migrations.AddField(
            model_name='costeo',
            name='IDRuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rutas.Rutas'),
        ),
        migrations.AddField(
            model_name='costeo',
            name='IDTransportista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Transportista.Transportista'),
        ),
        migrations.AddField(
            model_name='costeo',
            name='IDUnidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Transportista.Unidad'),
        ),
    ]
