# Generated by Django 2.1.12 on 2020-01-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoDisponible',
            fields=[
                ('IDEquipodisponible', models.AutoField(primary_key=True, serialize=False)),
                ('Disponibles', models.IntegerField(blank=True)),
                ('Ocupado', models.IntegerField(blank=True)),
                ('NoUnidades', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
