# Generated by Django 2.1.12 on 2020-01-03 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rutas', '0001_initial'),
        ('Transportista', '0001_initial'),
        ('Availability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipodisponible',
            name='Carrier',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='CarrierDisponible', to='Transportista.Transportista'),
        ),
        migrations.AddField(
            model_name='equipodisponible',
            name='rutas',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='EquipoDisponible', to='Rutas.Rutas'),
        ),
    ]
