# Generated by Django 2.1.12 on 2020-01-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admonusuarios',
            fields=[
                ('idusuario', models.AutoField(db_column='IDUsuario', primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(blank=True, db_column='NombreUsuario', max_length=200, null=True)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=200, null=True)),
                ('apepaterno', models.CharField(blank=True, db_column='ApePaterno', max_length=100, null=True)),
                ('apematerno', models.CharField(blank=True, db_column='ApeMaterno', max_length=100, null=True)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=200, null=True)),
                ('fechacambiocontrasena', models.DateTimeField(blank=True, db_column='FechaCambioContrasena', null=True)),
                ('hasbytes', models.TextField(blank=True, db_column='HasBytes', null=True)),
                ('saltbytes', models.TextField(blank=True, db_column='SaltBytes', null=True)),
                ('periodo', models.IntegerField(blank=True, db_column='Periodo', null=True)),
                ('statusreg', models.CharField(blank=True, db_column='StatusReg', max_length=20, null=True)),
            ],
            options={
                'db_table': 'AdmonUsuarios',
                'managed': False,
            },
        ),
    ]
